## 成绩从数据库获取到本地

In [3]:
import cx_Oracle
import pandas as pd
import molychin.database as mldb

### ★★★★★获取到处所有成绩的条件数据'XNM','XQM','XHH','CNT'，根据此数据，还可以分析专业建立和持续的时间

In [4]:
'''
cursor = mldb.moly_condb()
SQL1="select xnm,xqm,substr(xh_id,1,2) as xhh,count(*) as cnt \
      from zftal_jwlg.gjfx_view_full_cjb \
      group by xnm,xqm,substr(xh_id,1,2) \
      order by xnm,xqm,substr(xh_id,1,2)"

cursor.execute(SQL1)
print(cursor.statement)

cond_list=[]
for cn in cursor:
    cond_list.append([cn[0],cn[1],cn[2],cn[3]])
#print (cond_list)
cond_df=pd.DataFrame(cond_list,columns=['XNM','XQM','XHH','CNT'])
#cond_df.to_csv('data/cj_cond.csv',index=False)    #不保存索引
cond_df.to_csv('data/cj_cond.csv')    #保存索引
print('ok')
'''
#已完成

'\ncursor = mldb.moly_condb()\nSQL1="select xnm,xqm,substr(xh_id,1,2) as xhh,count(*) as cnt       from zftal_jwlg.gjfx_view_full_cjb       group by xnm,xqm,substr(xh_id,1,2)       order by xnm,xqm,substr(xh_id,1,2)"\n\ncursor.execute(SQL1)\nprint(cursor.statement)\n\ncond_list=[]\nfor cn in cursor:\n    cond_list.append([cn[0],cn[1],cn[2],cn[3]])\n#print (cond_list)\ncond_df=pd.DataFrame(cond_list,columns=[\'XNM\',\'XQM\',\'XHH\',\'CNT\'])\n#cond_df.to_csv(\'data/cj_cond.csv\',index=False)    #不保存索引\ncond_df.to_csv(\'data/cj_cond.csv\')    #保存索引\nprint(\'ok\')\n'

### 根据条件数据，逐步导出并追加数据到外部xscjb01.csv文件

In [5]:
#耗时45分钟
cursor = mldb.moly_condb()
cond_df=pd.read_csv('data/cj_cond.csv')
counter=0    #如果导出数据中断，从中断的地方开始，使用counter=1；将cj_cond.csv中已完成数据导出的条件删除。

print(pd.datetime.now())
for index,row in cond_df.iterrows():
    records=[]
    index=row[0]
    xnm=str(row['XNM'])
    xqm=str(row['XQM'])
    xhh=str(row['XHH'])
    cnt=row['CNT']
    print(index,xnm,xqm,xhh,cnt)

    SQL1="select * from zftal_jwlg.gjfx_view_full_cjb where xnm='"+xnm+"' and xqm='"+xqm+"' and substr(xh_id,1,2)='"+xhh+"'"
    cursor.execute(SQL1)
    print(cursor.statement)    #打印执行的语句

    for reco in cursor:
        record_list=[]
        for ii in range(len(reco)):
            record_list.append(reco[ii])
        records.append(record_list)

    if (counter==0):
        field_name_list=[]
        for field in cursor.description:
            field_name_list.append(field[0])
        xscjb_df=pd.DataFrame(records,columns=field_name_list)       
        xscjb_df.to_csv('data/xscjb02.csv',index=False)   
        counter=1
    else:
        xscjb_df=pd.DataFrame(records)
        xscjb_df.to_csv('data/xscjb02.csv',mode='a',header=0,index=False)   #追击数据模式，头部字段不用追加
    
    print('ok')

print(pd.datetime.now())

2019-02-15 16:50:25.271876
0 2003 12 04 6
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='12' and substr(xh_id,1,2)='04'
ok
1 2003 12 09 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='12' and substr(xh_id,1,2)='09'
ok
2 2003 12 16 9
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='12' and substr(xh_id,1,2)='16'
ok
3 2003 3 04 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='3' and substr(xh_id,1,2)='04'
ok
4 2003 3 07 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='3' and substr(xh_id,1,2)='07'
ok
5 2003 3 09 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='3' and substr(xh_id,1,2)='09'
ok
6 2003 3 16 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2003' and xqm='3' and substr(xh_id,1,2)='16'
ok
7 2004 12 04 10
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='04'
ok
8 2004 12 09 54
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='09'
ok
9 2004 12 15 17
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='15'
ok
10 2004 12 16 5
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='16'
ok
11 2004 12 17 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='17'
ok
12 2004 12 18 15
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='18'
ok
13 2004 12 Y0 5
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
14 2004 3 04 16
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='3' and substr(xh_id,1,2)='04'
ok
15 2004 3 09 43
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='3' and substr(xh_id,1,2)='09'
ok
16 2004 3 15 24
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='3' and substr(xh_id,1,2)='15'
ok
17 2004 3 16 19
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='3' and substr(xh_id,1,2)='16'
ok
18 2004 3 17 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='3' and substr(xh_id,1,2)='17'
ok
19 2004 3 18 11
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2004' and xqm='3' and substr(xh_id,1,2)='18'
ok
20 2005 12 01 2402
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='01'
ok
21 2005 12 02 3344
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='02'
ok
22 2005 12 03 3289
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='03'
ok
23 2005 12 04 1483
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='04'
ok
24 2005 12 05 2687
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='05'
ok
25 2005 12 06 4276
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='06'
ok
26 2005 12 07 3907
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='07'
ok
27 2005 12 08 1218
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='08'
ok
28 2005 12 09 3125
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='09'
ok
29 2005 12 15 2827
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='15'
ok
30 2005 12 16 2770
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='16'
ok
31 2005 12 17 1714
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='17'
ok
32 2005 12 18 2849
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='12' and substr(xh_id,1,2)='18'
ok
33 2005 3 01 1620
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='01'
ok
34 2005 3 02 2120
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='02'
ok
35 2005 3 03 1694
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='03'
ok
36 2005 3 04 1443
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='04'
ok
37 2005 3 05 2111
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='05'
ok
38 2005 3 06 3229
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='06'
ok
39 2005 3 07 2427
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='07'
ok
40 2005 3 08 968
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='08'
ok
41 2005 3 09 2050
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='09'
ok
42 2005 3 15 2318
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='15'
ok
43 2005 3 16 2000
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='16'
ok
44 2005 3 17 1046
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='17'
ok
45 2005 3 18 2166
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2005' and xqm='3' and substr(xh_id,1,2)='18'
ok
46 2006 12 01 7567
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='01'
ok
47 2006 12 02 6611
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='02'
ok
48 2006 12 03 7790
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='03'
ok
49 2006 12 04 5573
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='04'
ok
50 2006 12 05 7135
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='05'
ok
51 2006 12 06 8217
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='06'
ok
52 2006 12 07 9055
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='07'
ok
53 2006 12 08 3759
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='08'
ok
54 2006 12 09 7065
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='09'
ok
55 2006 12 11 1488
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='11'
ok
56 2006 12 13 290
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='13'
ok
57 2006 12 14 425
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='14'
ok
58 2006 12 15 7781
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='15'
ok
59 2006 12 16 7812
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='16'
ok
60 2006 12 17 5111
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='17'
ok
61 2006 12 18 5059
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='12' and substr(xh_id,1,2)='18'
ok
62 2006 3 01 7347
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='01'
ok
63 2006 3 02 8554
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='02'
ok
64 2006 3 03 8297
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='03'
ok
65 2006 3 04 6162
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='04'
ok
66 2006 3 05 9118
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='05'
ok
67 2006 3 06 9643
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='06'

ok
68 2006 3 07 10135
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='07'
ok
69 2006 3 08 3538
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='08'
ok
70 2006 3 09 7618
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='09'
ok
71 2006 3 11 1553
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='11'
ok
72 2006 3 13 466
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='13'
ok
73 2006 3 14 1084
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='14'
ok
74 2006 3 15 8780
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='15'
ok
75 2006 3 16 8075
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='16'
ok
76 2006 3 17 4783
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='17'
ok
77 2006 3 18 5362
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2006' and xqm='3' and substr(xh_id,1,2)='18'
ok
78 2007 12 01 7418
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='01'
ok
79 2007 12 02 8040
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='02'
ok
80 2007 12 03 8916
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='03'
ok
81 2007 12 04 5879
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='04'
ok
82 2007 12 05 7303
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='05'
ok
83 2007 12 06 8482
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='06'
ok
84 2007 12 07 9418
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='07'
ok
85 2007 12 08 4702
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='08'
ok
86 2007 12 09 7713
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='09'
ok
87 2007 12 11 513
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='11'
ok
88 2007 12 13 188
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='13'
ok
89 2007 12 14 18
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='14'
ok
90 2007 12 15 8118
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='15'
ok
91 2007 12 16 7106
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='16'
ok
92 2007 12 17 6032
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='17'
ok
93 2007 12 18 5138
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='18'
ok
94 2007 12 Y0 11185
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
95 2007 12 Y1 3463
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
96 2007 3 01 7019
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='01'
ok
97 2007 3 02 9446
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='02'
ok
98 2007 3 03 8544
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='03'
ok
99 2007 3 04 6218
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='04'
ok
100 2007 3 05 8238
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='05'
ok
101 2007 3 06 9209
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='06'
ok
102 2007 3 07 11152
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='07'
ok
103 2007 3 08 4456
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='08'
ok
104 2007 3 09 7831
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='09'
ok
105 2007 3 11 771
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='11'
ok
106 2007 3 13 96
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='13'
ok
107 2007 3 14 22
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='14'
ok
108 2007 3 15 9378
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='15'
ok
109 2007 3 16 9458
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='16'
ok
110 2007 3 17 5524
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='17'
ok
111 2007 3 18 3860
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='18'
ok
112 2007 3 Y0 8872
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
113 2007 3 Y1 3751
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2007' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
114 2008 12 01 9147
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='01'
ok
115 2008 12 02 11375
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='02'
ok
116 2008 12 03 7984
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='03'
ok
117 2008 12 04 7391
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='04'
ok
118 2008 12 05 7829
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='05'
ok
119 2008 12 06 8740
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='06'
ok
120 2008 12 07 11191
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='07'
ok
121 2008 12 08 6086
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='08'
ok
122 2008 12 09 8991
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='09'
ok
123 2008 12 14 2
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='14'
ok
124 2008 12 15 9555
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='15'
ok
125 2008 12 16 9792
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='16'
ok
126 2008 12 17 5810
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='17'
ok
127 2008 12 18 5226
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='18'
ok
128 2008 12 Y0 21128
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
129 2008 12 Y1 6055
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
130 2008 3 01 7614
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='01'
ok
131 2008 3 02 9783
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='02'
ok
132 2008 3 03 8103
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='03'
ok
133 2008 3 04 5489
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='04'
ok
134 2008 3 05 8166
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='05'

ok
135 2008 3 06 8026
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='06'
ok
136 2008 3 07 11777
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='07'
ok
137 2008 3 08 5834
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='08'
ok
138 2008 3 09 9926
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='09'
ok
139 2008 3 15 8504
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='15'
ok
140 2008 3 16 9860
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='16'
ok
141 2008 3 17 5668
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='17'
ok
142 2008 3 18 4969
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='18'
ok
143 2008 3 Y0 17401
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
144 2008 3 Y1 5268
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2008' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
145 2009 12 01 8932
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='01'
ok
146 2009 12 02 11332
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='02'
ok
147 2009 12 03 7307
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='03'
ok
148 2009 12 04 7204
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='04'
ok
149 2009 12 05 8837
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='05'
ok
150 2009 12 06 8594
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='06'
ok
151 2009 12 07 10022
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='07'
ok
152 2009 12 08 5991
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='08'
ok
153 2009 12 09 9556
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='09'
ok
154 2009 12 15 8367
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='15'
ok
155 2009 12 16 12121
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='16'
ok
156 2009 12 17 5787
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='17'
ok
157 2009 12 18 3228
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='18'
ok
158 2009 12 Y0 29588
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
159 2009 12 Y1 9235
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
160 2009 3 01 8809
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='01'
ok
161 2009 3 02 11905
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='02'
ok
162 2009 3 03 6930
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='03'
ok
163 2009 3 04 6601
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='04'
ok
164 2009 3 05 7808
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='05'
ok
165 2009 3 06 9047
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='06'
ok
166 2009 3 07 10397
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='07'
ok
167 2009 3 08 6878
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='08'
ok
168 2009 3 09 10239
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='09'
ok
169 2009 3 15 7989
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='15'
ok
170 2009 3 16 11994
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='16'
ok
171 2009 3 17 6573
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='17'
ok
172 2009 3 18 3348
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='18'
ok
173 2009 3 Y0 26481
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
174 2009 3 Y1 8796
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2009' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
175 2010 12 01 9240
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='01'
ok
176 2010 12 02 12101
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='02'
ok
177 2010 12 03 7552
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='03'
ok
178 2010 12 04 6790
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='04'
ok
179 2010 12 05 9293
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='05'
ok
180 2010 12 06 9662
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='06'
ok
181 2010 12 07 11187
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='07'
ok
182 2010 12 08 6864
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='08'
ok
183 2010 12 09 12205
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='09'
ok
184 2010 12 15 8788
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='15'
ok
185 2010 12 16 13646
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='16'
ok
186 2010 12 17 6347
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='17'
ok
187 2010 12 18 1887
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='18'
ok
188 2010 12 PT 15
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='PT'
ok
189 2010 12 Y0 31757
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
190 2010 12 Y1 11160
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
191 2010 12 YZ 1683
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='12' and substr(xh_id,1,2)='YZ'
ok
192 2010 3 01 8890
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='01'
ok
193 2010 3 02 11610
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='02'
ok
194 2010 3 03 6884
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='03'
ok
195 2010 3 04 6227
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='04'
ok
196 2010 3 05 8363
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='05'
ok
197 2010 3 06 9457
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='06'
ok
198 2010 3 07 11034
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='07'
ok
199 2010 3 08 7389
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='08'
ok
200 2010 3 09 9522
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='09'
ok
201 2010 3 15 8351
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='15'

ok
202 2010 3 16 13911
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='16'
ok
203 2010 3 17 6610
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='17'
ok
204 2010 3 18 1171
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='18'
ok
205 2010 3 PT 14
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='PT'
ok
206 2010 3 Y0 30798
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
207 2010 3 Y1 11388
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
208 2010 3 YZ 1777
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2010' and xqm='3' and substr(xh_id,1,2)='YZ'
ok
209 2011 12 01 9831
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='01'
ok
210 2011 12 02 11792
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='02'
ok
211 2011 12 03 7397
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='03'
ok
212 2011 12 04 6810
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='04'
ok
213 2011 12 05 10124
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='05'
ok
214 2011 12 06 10406
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='06'
ok
215 2011 12 07 12070
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='07'
ok
216 2011 12 08 8150
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='08'
ok
217 2011 12 09 13080
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='09'
ok
218 2011 12 15 10257
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='15'
ok
219 2011 12 16 13781
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='16'
ok
220 2011 12 17 7274
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='17'
ok
221 2011 12 18 571
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='18'
ok
222 2011 12 PT 6
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='PT'
ok
223 2011 12 Y0 33084
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
224 2011 12 Y1 15240
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
225 2011 12 YZ 2798
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='12' and substr(xh_id,1,2)='YZ'
ok
226 2011 3 01 8672
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='01'
ok
227 2011 3 02 11964
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='02'
ok
228 2011 3 03 7282
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='03'
ok
229 2011 3 04 5762
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='04'
ok
230 2011 3 05 8955
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='05'
ok
231 2011 3 06 9431
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='06'
ok
232 2011 3 07 12241
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='07'
ok
233 2011 3 08 7242
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='08'
ok
234 2011 3 09 11773
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='09'
ok
235 2011 3 15 8616
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='15'
ok
236 2011 3 16 13940
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='16'
ok
237 2011 3 17 7633
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='17'
ok
238 2011 3 18 276
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='18'
ok
239 2011 3 PT 12
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='PT'
ok
240 2011 3 Y0 29405
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
241 2011 3 Y1 14419
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
242 2011 3 YZ 3727
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2011' and xqm='3' and substr(xh_id,1,2)='YZ'
ok
243 2012 12 01 9057
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='01'
ok
244 2012 12 02 12704
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='02'
ok
245 2012 12 03 7891
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='03'
ok
246 2012 12 04 6057
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='04'
ok
247 2012 12 05 11276
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='05'
ok
248 2012 12 06 9847
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='06'
ok
249 2012 12 07 12434
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='07'
ok
250 2012 12 08 8167
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='08'
ok
251 2012 12 09 12189
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='09'
ok
252 2012 12 15 11079
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='15'
ok
253 2012 12 16 12909
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='16'
ok
254 2012 12 17 7830
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='17'
ok
255 2012 12 18 17
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='18'
ok
256 2012 12 PT 22
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='PT'
ok
257 2012 12 Y0 26144
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
258 2012 12 Y1 16817
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
259 2012 12 YZ 3739
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='12' and substr(xh_id,1,2)='YZ'
ok
260 2012 3 01 7936
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='01'
ok
261 2012 3 02 12196
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='02'
ok
262 2012 3 03 6907
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='03'
ok
263 2012 3 04 5822
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='04'
ok
264 2012 3 05 8953
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='05'
ok
265 2012 3 06 9475
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='06'
ok
266 2012 3 07 11682
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='07'
ok
267 2012 3 08 7726
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='08'
ok
268 2012 3 09 10500
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='09'

ok
269 2012 3 15 10305
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='15'
ok
270 2012 3 16 13468
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='16'
ok
271 2012 3 17 8065
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='17'
ok
272 2012 3 18 16
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='18'
ok
273 2012 3 PT 246
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='PT'
ok
274 2012 3 Y0 24817
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
275 2012 3 Y1 14515
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
276 2012 3 YZ 5112
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2012' and xqm='3' and substr(xh_id,1,2)='YZ'
ok
277 2013 12 01 9045
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='01'
ok
278 2013 12 02 12557
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='02'
ok
279 2013 12 03 9470
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='03'
ok
280 2013 12 04 6806
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='04'
ok
281 2013 12 05 11240
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='05'
ok
282 2013 12 06 11632
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='06'
ok
283 2013 12 07 12214
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='07'
ok
284 2013 12 08 8665
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='08'
ok
285 2013 12 09 13181
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='09'
ok
286 2013 12 15 11915
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='15'
ok
287 2013 12 16 13324
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='16'
ok
288 2013 12 17 8091
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='17'
ok
289 2013 12 18 9
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='18'
ok
290 2013 12 PT 173
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='PT'
ok
291 2013 12 Y0 20117
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
292 2013 12 Y1 12384
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
293 2013 12 YZ 852
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='YZ'
ok
294 2013 12 ZB 5086
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='12' and substr(xh_id,1,2)='ZB'
ok
295 2013 3 01 7678
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='01'
ok
296 2013 3 02 10638
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='02'
ok
297 2013 3 03 8061
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='03'
ok
298 2013 3 04 6001
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='04'
ok
299 2013 3 05 9440
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='05'
ok
300 2013 3 06 10176
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='06'
ok
301 2013 3 07 12081
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='07'
ok
302 2013 3 08 7760
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='08'
ok
303 2013 3 09 10879
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='09'
ok
304 2013 3 15 10642
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='15'
ok
305 2013 3 16 12205
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='16'
ok
306 2013 3 17 8120
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='17'
ok
307 2013 3 18 4
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='18'
ok
308 2013 3 PT 261
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='PT'
ok
309 2013 3 Y0 19395
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
310 2013 3 Y1 11096
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
311 2013 3 YZ 2827
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='YZ'
ok
312 2013 3 ZB 4774
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2013' and xqm='3' and substr(xh_id,1,2)='ZB'
ok
313 2014 12 01 9388
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='01'
ok
314 2014 12 02 15306
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='02'
ok
315 2014 12 03 11229
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='03'
ok
316 2014 12 04 7482
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='04'
ok
317 2014 12 05 10341
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='05'
ok
318 2014 12 06 10800
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='06'
ok
319 2014 12 07 13185
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='07'
ok
320 2014 12 08 8101
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='08'
ok
321 2014 12 09 12479
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='09'
ok
322 2014 12 15 11192
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='15'
ok
323 2014 12 16 12936
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='16'
ok
324 2014 12 17 7765
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='17'
ok
325 2014 12 PT 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='PT'
ok
326 2014 12 Y0 11396
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
327 2014 12 Y1 7091
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
328 2014 12 YZ 3
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='YZ'
ok
329 2014 12 Z0 5103
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='Z0'
ok
330 2014 12 Z1 1597
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='Z1'
ok
331 2014 12 ZB 4904
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='12' and substr(xh_id,1,2)='ZB'
ok
332 2014 3 01 7918
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='01'
ok
333 2014 3 02 13585
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='02'
ok
334 2014 3 03 9635
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='03'
ok
335 2014 3 04 6709
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='04'

ok
336 2014 3 05 9237
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='05'
ok
337 2014 3 06 10869
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='06'
ok
338 2014 3 07 12890
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='07'
ok
339 2014 3 08 8136
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='08'
ok
340 2014 3 09 11120
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='09'
ok
341 2014 3 15 11363
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='15'
ok
342 2014 3 16 11928
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='16'
ok
343 2014 3 17 7298
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='17'
ok
344 2014 3 PT 59
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='PT'
ok
345 2014 3 Y0 11645
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
346 2014 3 Y1 6040
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
347 2014 3 YZ 10
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='YZ'
ok
348 2014 3 Z0 3587
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='Z0'
ok
349 2014 3 Z1 1438
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='Z1'
ok
350 2014 3 ZB 7141
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2014' and xqm='3' and substr(xh_id,1,2)='ZB'
ok
351 2015 12 01 8232
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='01'
ok
352 2015 12 02 17630
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='02'
ok
353 2015 12 03 12767
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='03'
ok
354 2015 12 04 7978
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='04'
ok
355 2015 12 05 9461
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='05'
ok
356 2015 12 06 10541
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='06'
ok
357 2015 12 07 13786
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='07'
ok
358 2015 12 08 10096
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='08'
ok
359 2015 12 09 10813
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='09'
ok
360 2015 12 15 11761
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='15'
ok
361 2015 12 16 11688
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='16'
ok
362 2015 12 17 9089
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='17'
ok
363 2015 12 PT 221
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='PT'
ok
364 2015 12 Y0 5288
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
365 2015 12 Y1 2951
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
366 2015 12 Z0 9420
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='Z0'
ok
367 2015 12 Z1 3497
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='Z1'
ok
368 2015 12 ZB 6139
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='12' and substr(xh_id,1,2)='ZB'
ok
369 2015 3 01 7482
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='01'
ok
370 2015 3 02 16520
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='02'
ok
371 2015 3 03 11823
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='03'
ok
372 2015 3 04 7591
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='04'
ok
373 2015 3 05 8268
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='05'
ok
374 2015 3 06 10964
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='06'
ok
375 2015 3 07 13980
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='07'
ok
376 2015 3 08 9101
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='08'
ok
377 2015 3 09 10410
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='09'
ok
378 2015 3 15 11280
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='15'
ok
379 2015 3 16 11860
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='16'
ok
380 2015 3 17 7917
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='17'
ok
381 2015 3 PT 186
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='PT'
ok
382 2015 3 Y0 5218
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
383 2015 3 Y1 2515
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
384 2015 3 Z0 8561
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='Z0'
ok
385 2015 3 Z1 3615
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='Z1'
ok
386 2015 3 ZB 7190
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2015' and xqm='3' and substr(xh_id,1,2)='ZB'
ok
387 2016 12 01 7663
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='01'
ok
388 2016 12 02 21840
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='02'
ok
389 2016 12 03 13066
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='03'
ok
390 2016 12 04 9351
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='04'
ok
391 2016 12 05 9300
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='05'
ok
392 2016 12 06 10479
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='06'
ok
393 2016 12 07 14853
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='07'
ok
394 2016 12 08 10344
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='08'
ok
395 2016 12 09 10297
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='09'
ok
396 2016 12 15 11528
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='15'
ok
397 2016 12 16 10793
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='16'
ok
398 2016 12 17 10955
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='17'
ok
399 2016 12 PT 115
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='PT'
ok
400 2016 12 Y0 1543
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
401 2016 12 Y1 575
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
402 2016 12 Z0 13272
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='Z0'

ok
403 2016 12 Z1 4873
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='Z1'
ok
404 2016 12 ZB 7657
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='12' and substr(xh_id,1,2)='ZB'
ok
405 2016 3 01 6370
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='01'
ok
406 2016 3 02 20669
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='02'
ok
407 2016 3 03 11261
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='03'
ok
408 2016 3 04 9292
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='04'
ok
409 2016 3 05 8945
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='05'
ok
410 2016 3 06 10420
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='06'
ok
411 2016 3 07 16479
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='07'
ok
412 2016 3 08 9615
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='08'
ok
413 2016 3 09 9820
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='09'
ok
414 2016 3 15 11706
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='15'
ok
415 2016 3 16 11237
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='16'
ok
416 2016 3 17 10303
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='17'
ok
417 2016 3 PT 63
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='PT'
ok
418 2016 3 Y0 1993
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
419 2016 3 Y1 476
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
420 2016 3 Z0 12877
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='Z0'
ok
421 2016 3 Z1 5283
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='Z1'
ok
422 2016 3 ZB 9265
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2016' and xqm='3' and substr(xh_id,1,2)='ZB'
ok
423 2017 12 01 6583
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='01'
ok
424 2017 12 02 25929
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='02'
ok
425 2017 12 03 13380
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='03'
ok
426 2017 12 04 9787
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='04'
ok
427 2017 12 05 9156
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='05'
ok
428 2017 12 06 10762
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='06'
ok
429 2017 12 07 16077
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='07'
ok
430 2017 12 08 10481
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='08'
ok
431 2017 12 09 9413
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='09'
ok
432 2017 12 15 12318
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='15'
ok
433 2017 12 16 10766
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='16'
ok
434 2017 12 17 12953
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='17'
ok
435 2017 12 58 4
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='58'
ok
436 2017 12 66 9
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='66'
ok
437 2017 12 LX 307
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='LX'
ok
438 2017 12 P1 3
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='P1'
ok
439 2017 12 PT 13
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='PT'
ok
440 2017 12 Y0 77
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='Y0'
ok
441 2017 12 Y1 30
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='Y1'
ok
442 2017 12 Z0 14010
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='Z0'
ok
443 2017 12 Z1 5724
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='Z1'
ok
444 2017 12 ZB 9956
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='12' and substr(xh_id,1,2)='ZB'
ok
445 2017 3 01 5847
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='01'
ok
446 2017 3 02 23448
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='02'
ok
447 2017 3 03 12138
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='03'
ok
448 2017 3 04 9737
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='04'
ok
449 2017 3 05 8976
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='05'
ok
450 2017 3 06 10745
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='06'
ok
451 2017 3 07 18211
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='07'
ok
452 2017 3 08 9887
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='08'
ok
453 2017 3 09 9479
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='09'
ok
454 2017 3 15 11166
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='15'
ok
455 2017 3 16 12153
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='16'
ok
456 2017 3 17 12407
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='17'
ok
457 2017 3 58 17
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='58'
ok
458 2017 3 LX 364
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='LX'
ok
459 2017 3 P0 1
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='P0'
ok
460 2017 3 P1 30
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='P1'
ok
461 2017 3 PT 97
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='PT'
ok
462 2017 3 Y0 116
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
463 2017 3 Y1 34
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
464 2017 3 Z0 14639
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='Z0'
ok
465 2017 3 Z1 5347
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='Z1'
ok
466 2017 3 ZB 11681
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2017' and xqm='3' and substr(xh_id,1,2)='ZB'
ok
467 2018 12 02 1
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='12' and substr(xh_id,1,2)='02'
ok
468 2018 3 01 5147
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='01'
ok
469 2018 3 02 24172
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='02'

ok
470 2018 3 03 12538
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='03'
ok
471 2018 3 04 9277
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='04'
ok
472 2018 3 05 8596
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='05'
ok
473 2018 3 06 12558
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='06'
ok
474 2018 3 07 17689
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='07'
ok
475 2018 3 08 8463
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='08'
ok
476 2018 3 09 8447
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='09'
ok
477 2018 3 15 12463
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='15'
ok
478 2018 3 16 12234
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='16'
ok
479 2018 3 17 14379
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='17'
ok
480 2018 3 58 6
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='58'
ok
481 2018 3 66 11
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='66'
ok
482 2018 3 75 14
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='75'
ok
483 2018 3 76 4
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='76'
ok
484 2018 3 77 8
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='77'
ok
485 2018 3 LX 175
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='LX'
ok
486 2018 3 P0 7
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='P0'
ok
487 2018 3 P1 3
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='P1'
ok
488 2018 3 PT 26
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='PT'
ok
489 2018 3 Y0 17
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='Y0'
ok
490 2018 3 Y1 10
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='Y1'
ok
491 2018 3 Z0 13656
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='Z0'
ok
492 2018 3 Z1 5220
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='Z1'
ok
493 2018 3 ZB 11803
select * from zftal_jwlg.gjfx_view_full_cjb where xnm='2018' and xqm='3' and substr(xh_id,1,2)='ZB'
ok
2019-02-15 17:35:32.014693

#### 已完成